name: "patoughi-driver"

services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
      secrets:
        - composer_auth
    image: patoughi/platform-tms-api:development
    restart: unless-stopped
    command: [
      "php",
      "artisan",
      "octane:frankenphp",
      "--log-level=info"
    ]
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - patoughi
    ports:
      # HTTP
      - target: 8000
        published: ${HTTP_PORT:-8000}
        protocol: tcp
  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'mysql-data:/var/lib/mysql'
    networks:
      - patoughi
    ports:
      - '${MYSQL_PORT:-3306}:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s

  # phpMyAdmin Container
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root  # Must match the root password above
      UPLOAD_LIMIT: 20000M
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - patoughi

  redis:
    image: 'redis:alpine'
    restart: unless-stopped
    volumes:
      - 'redis-data:/data'
    networks:
      - patoughi
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
    ports:
      - '${REDIS_PORT:-6379}:6379'
  minio:
    image: 'minio/minio:latest'
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: magnet
      MINIO_ROOT_PASSWORD: password
    volumes:
      - 'minio-data:/data/minio'
    networks:
      - patoughi
    command: 'minio server /data/minio --console-address ":8900"'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:9000/minio/health/live'
      retries: 3
      timeout: 5s
    ports:
      - '${MINIO_PORT:-9000}:9000'
      - '${MINIO_CONSOLE_PORT:-8900}:8900'
networks:
  patoughi:
    external: true
volumes:
  mysql-data:
  redis-data:
  minio-data:
secrets:
  composer_auth:
    file: ./auth.json
